# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 21600s

steps:
  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: terraform
    args: ["version"]
    id: Terraform version

  # folder/cicd
  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: terraform
    args: ["init"]
    dir: "${_TERRAFORM_ROOT}/folder/cicd"
    id: Init (CICD)

  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: terraform
    args: ["plan"]
    dir: "${_TERRAFORM_ROOT}/folder/cicd"
    id: Speculative plan (CICD)

  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: terraform
    args: ["apply", "-auto-approve"]
    dir: "${_TERRAFORM_ROOT}/folder/cicd"
    id: Deployment (CICD)

  # folder/
  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: terragrunt
    args: ["init"]
    dir: "${_TERRAFORM_ROOT}/folder"
    id: Init (folder)

  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: bash
    args: ["../cicd/configs/terragrunt.sh", "plan-all"]
    dir: "${_TERRAFORM_ROOT}/folder"
    id: Speculative plan (folder)

  - name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
    entrypoint: bash
    args: ["../cicd/configs/terragrunt.sh", "apply-all"]
    dir: "${_TERRAFORM_ROOT}/folder"
    id: Deployment (folder)

substitutions:
    _TERRAFORM_ROOT: "."
