steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/triggers-pubsub-handler', '.']
  dir: "data-processing/firestore/real_time_triggers/subscriber"

images: ['gcr.io/$PROJECT_ID/triggers-pubsub-handler']
